channels:
# - conda-forge
- main
dependencies:
- autopep8=1.5.4
- beautifulsoup4=4.9.3
- click=7.1.2
- codecov=2.1.10
- dill=0.3.2
- docopt=0.6.2
# - flake8-isort=4.0.0
- flake8=3.8.4
# - geckodriver=0.27.0
- ipython=7.18.1
# - js2py=0.70
# - leveldb=1.22
# - localstack=0.11.1.1
# - multiprocess=0.70.10
# - nodejs=14.14.0
- pandas=1.1.3
- pillow=8.0.1
- pip=20.2.4
# - pre-commit=2.8.1
# - psutil=5.7.3
- pyarrow=2.0.0
- pytest-cov=2.10.1
- pytest=6.1.2
# - python=3.8.6
# - pyvirtualdisplay=0.2.5
- redis-py=3.5.3
- s3fs=0.4.0
- selenium=3.141.0
# - sentry-sdk=0.19.1
- tabulate=0.8.7
- tblib=1.6.0
- wget=1.20.1
# - Js2Py=0.70
- numpy=1.19.5
# - Pebble=4.6.3
- requests=2.25.1
- scikit-learn=0.24.1
- tqdm=4.59.0
- pip:
  - amazon-kclpy==2.0.1
  - crontab==0.22.9
  - domain-utils==0.7.1
  - flask-cors==3.0.9
  - jsonschema==3.2.0
  - moto-ext==1.3.15.15
  - plyvel==1.3.0
  - subprocess32==3.5.4
name: openwpm
